name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.3
  - mlflow=1.25.1
  - numpy=1.20.3
  - pandas=1.3.4
  - pip=21.2.4
  - python=3.9.7
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - pip:
    - azureml==0.2.7
    - azureml-core==1.40.0
    - azureml-flow==1.40.0
    - influxdb==5.3.1
    - mlflow-skinny==1.25.1
    - xgboost==1.6.0
